### ISSUE TITLE
v1.0 roadmap

### ISSUE THREAD

**Issue by nebulaa44** [nebulaa44/sysfetch#2]
- [ ] Distro information (name, version)
- [ ] Terminal detection (name)
- [ ] Configuration (what fields to display)
- [ ] Shell (name, version)
